#!/bin/sh

dest_dir="$1"
src_dir="`dirname $0`"

if [ ! -d "$dest_dir" ]; then

  echo "$dest_dir doesn't exist"
  exit 1

fi

hooks="${dest_dir}/.git/hooks"

if [ ! -d "$hooks" ]; then

  echo "$hooks doesn't exist"
  exit 1

fi

if [ -e "${hooks}/post-commit" -o -e "${hooks}/post-checkout" -o -e "${hooks}/post-merge" ]; then

  echo "One of ${hooks}/post-{commit,checkout,merge} hooks already exist"
  echo "You will have to setup gitperms manually"
  exit 1

fi

cp "${src_dir}/post-commit" "${src_dir}/post-checkout" "$hooks"
ln -s post-checkout "${hooks}/post-merge"
cp "${src_dir}/handle_metadata" "$hooks"
chmod 0755 "${hooks}/post-commit" "${hooks}/post-checkout" "${hooks}/handle_metadata"

cd "$dest_dir"

git config --add remote.origin.fetch '+refs/tags/*:regs/tags/*'
git config --add remote.origin.fetch '+refs/notes/*:refs/notes/*'
git config --add remote.origin.push '+refs/heads/*:refs/heads/*'
git config --add remote.origin.push '+refs/tags/*:refs/tags/*'
git config --add remote.origin.push '+refs/notes/*:refs/notes/*'
