#!/bin/bash

dest_dir=$1
src_dir=$(dirname $0)

if [[ ! -d $dest_dir ]]; then

  echo "$dest_dir doesn't exist"
  exit 1

fi

hooks="${dest_dir}/.git/hooks"

if [[ ! -d $hooks ]]; then

  echo "$hooks doesn't exist"
  exit 1

fi

if [[ -e "${hooks}/post-commit" ]]; then

  echo "post-commit already exists in ${hooks}, skipping"

else

  cp "${src_dir}/post-commit" $hooks

fi

if [[ -e "${hooks}/post-checkout" ]]; then

  echo "post-checkout already exists in ${hooks}, skipping"

else

  cp "${src_dir}/post-checkout" $hooks

fi

if [[ -e "${hooks}/post-merge" ]]; then

  echo "post-merge already exists in ${hooks}, skipping"

else

  ln -s "${hooks}/post-checkout" "${hooks}/post-merge"

fi

cp "${src_dir}/handle-metadata" $hooks

cd $dest_dir

git config --add remote.origin.fetch '+refs/tags/*:regs/tags/*'
git config --add remote.origin.fetch '+refs/notes/*:refs/notes/*'
git config --add remote.origin.push '+refs/heads/*:refs/heads/*'
git config --add remote.origin.push '+refs/tags/*:refs/tags/*'
git config --add remote.origin.push '+refs/notes/*:refs/notes/*'
